# Generated by Django 2.2.24 on 2021-10-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
